[features]
seeds = true
skip-lint = false

[programs.localnet]
swap_program = "FVCG6YkMbACgskY3ZrwqWFr45ERgJuKrf7C9dRDh6LjX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/joesol/.config/solana/id.json"

[scripts]
upload-json = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/upload-json.test.ts"
create-assets = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/create-assets.test.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/main.test.ts"
master = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/master.test.ts"